# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photobooth.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhotoBooth(object):
    def setupUi(self, PhotoBooth):
        PhotoBooth.setObjectName("PhotoBooth")
        PhotoBooth.resize(1920, 1080)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 187, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 187, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 184, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        PhotoBooth.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        PhotoBooth.setFont(font)
        PhotoBooth.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.logo1 = QtWidgets.QLabel(PhotoBooth)
        self.logo1.setGeometry(QtCore.QRect(0, 25, 150, 169))
        self.logo1.setText("")
        self.logo1.setPixmap(QtGui.QPixmap("ressources/logo_blanc_sur_transparent.png"))
        self.logo1.setScaledContents(True)
        self.logo1.setObjectName("logo1")
        self.compteur = QtWidgets.QLabel(PhotoBooth)
        self.compteur.setGeometry(QtCore.QRect(0, 859, 150, 211))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.compteur.setFont(font)
        self.compteur.setAcceptDrops(False)
        self.compteur.setTextFormat(QtCore.Qt.AutoText)
        self.compteur.setAlignment(QtCore.Qt.AlignCenter)
        self.compteur.setObjectName("compteur")
        self.loading = QtWidgets.QLabel(PhotoBooth)
        self.loading.setGeometry(QtCore.QRect(760, 340, 400, 400))
        self.loading.setText("")
        self.loading.setObjectName("loading")
        self.background = QtWidgets.QLabel(PhotoBooth)
        self.background.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Forfty Scribble")
        font.setBold(True)
        font.setWeight(75)
        self.background.setFont(font)
        self.background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(222, 180, 163, 255), stop:1 rgba(242, 199, 183, 255));")
        self.background.setText("")
        self.background.setObjectName("background")
        self.widgetPrint = QtWidgets.QWidget(PhotoBooth)
        self.widgetPrint.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.widgetPrint.setObjectName("widgetPrint")
        self.nbPrintLabel = QtWidgets.QLabel(self.widgetPrint)
        self.nbPrintLabel.setGeometry(QtCore.QRect(1770, 320, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.nbPrintLabel.setFont(font)
        self.nbPrintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbPrintLabel.setObjectName("nbPrintLabel")
        self.buttonIncrease = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonIncrease.setGeometry(QtCore.QRect(1859, 480, 61, 111))
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.buttonIncrease.setFont(font)
        self.buttonIncrease.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.buttonIncrease.setObjectName("buttonIncrease")
        self.buttonPrinter = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonPrinter.setGeometry(QtCore.QRect(1770, 630, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.buttonPrinter.setFont(font)
        self.buttonPrinter.setAutoFillBackground(False)
        self.buttonPrinter.setStyleSheet("background-color: transparent;")
        self.buttonPrinter.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/boutonPrinter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrinter.setIcon(icon)
        self.buttonPrinter.setIconSize(QtCore.QSize(150, 150))
        self.buttonPrinter.setObjectName("buttonPrinter")
        self.buttonRestart = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonRestart.setGeometry(QtCore.QRect(0, 430, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.buttonRestart.setFont(font)
        self.buttonRestart.setAutoFillBackground(False)
        self.buttonRestart.setStyleSheet("background-color: transparent;")
        self.buttonRestart.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ressources/boutonRestart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRestart.setIcon(icon1)
        self.buttonRestart.setIconSize(QtCore.QSize(150, 150))
        self.buttonRestart.setObjectName("buttonRestart")
        self.buttonCancel = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonCancel.setGeometry(QtCore.QRect(0, 600, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setAutoFillBackground(False)
        self.buttonCancel.setStyleSheet("background-color: transparent;")
        self.buttonCancel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ressources/boutonCancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCancel.setIcon(icon2)
        self.buttonCancel.setIconSize(QtCore.QSize(150, 150))
        self.buttonCancel.setObjectName("buttonCancel")
        self.buttonDecrease = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonDecrease.setGeometry(QtCore.QRect(1770, 480, 61, 111))
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(60)
        font.setBold(True)
        font.setWeight(75)
        self.buttonDecrease.setFont(font)
        self.buttonDecrease.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.buttonDecrease.setObjectName("buttonDecrease")
        self.viewer = QtWidgets.QLabel(self.widgetPrint)
        self.viewer.setGeometry(QtCore.QRect(150, 0, 1620, 1080))
        self.viewer.setAutoFillBackground(False)
        self.viewer.setText("")
        self.viewer.setObjectName("viewer")
        self.viewer.raise_()
        self.nbPrintLabel.raise_()
        self.buttonIncrease.raise_()
        self.buttonPrinter.raise_()
        self.buttonRestart.raise_()
        self.buttonCancel.raise_()
        self.buttonDecrease.raise_()
        self.widgetDevelopper = QtWidgets.QWidget(PhotoBooth)
        self.widgetDevelopper.setGeometry(QtCore.QRect(1770, 0, 150, 111))
        self.widgetDevelopper.setObjectName("widgetDevelopper")
        self.buttonExit = QtWidgets.QPushButton(self.widgetDevelopper)
        self.buttonExit.setGeometry(QtCore.QRect(0, 0, 150, 70))
        self.buttonExit.setStyleSheet("background-color: transparent;")
        self.buttonExit.setText("")
        self.buttonExit.setObjectName("buttonExit")
        self.warning = QtWidgets.QLabel(self.widgetDevelopper)
        self.warning.setGeometry(QtCore.QRect(0, 70, 150, 31))
        self.warning.setObjectName("warning")
        self.widgetPhoto = QtWidgets.QWidget(PhotoBooth)
        self.widgetPhoto.setGeometry(QtCore.QRect(150, 0, 1920, 1080))
        self.widgetPhoto.setObjectName("widgetPhoto")
        self.buttonPhoto = QtWidgets.QPushButton(self.widgetPhoto)
        self.buttonPhoto.setGeometry(QtCore.QRect(1620, 460, 150, 150))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.buttonPhoto.setFont(font)
        self.buttonPhoto.setAutoFillBackground(False)
        self.buttonPhoto.setStyleSheet("background-color: transparent;")
        self.buttonPhoto.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ressources/boutonPhoto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPhoto.setIcon(icon3)
        self.buttonPhoto.setIconSize(QtCore.QSize(150, 150))
        self.buttonPhoto.setObjectName("buttonPhoto")
        self.countdown = QtWidgets.QLabel(self.widgetPhoto)
        self.countdown.setGeometry(QtCore.QRect(0, 200, 1620, 700))
        font = QtGui.QFont()
        font.setPointSize(500)
        self.countdown.setFont(font)
        self.countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.countdown.setObjectName("countdown")
        self.camView = QtWidgets.QLabel(self.widgetPhoto)
        self.camView.setGeometry(QtCore.QRect(0, 0, 1620, 1080))
        self.camView.setAutoFillBackground(False)
        self.camView.setText("")
        self.camView.setObjectName("camView")
        self.lookUp = QtWidgets.QLabel(self.widgetPhoto)
        self.lookUp.setGeometry(QtCore.QRect(0, 0, 1620, 280))
        font = QtGui.QFont()
        font.setPointSize(160)
        self.lookUp.setFont(font)
        self.lookUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lookUp.setObjectName("lookUp")
        self.buttonPhoto.raise_()
        self.camView.raise_()
        self.countdown.raise_()
        self.lookUp.raise_()
        self.veilleButton = QtWidgets.QPushButton(PhotoBooth)
        self.veilleButton.setGeometry(QtCore.QRect(-20, -20, 1960, 1120))
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(72)
        self.veilleButton.setFont(font)
        self.veilleButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(222, 180, 163, 255), stop:1 rgba(242, 199, 183, 255));\n"
"color: rgb(255, 255, 255);")
        self.veilleButton.setObjectName("veilleButton")
        self.logo2 = QtWidgets.QLabel(PhotoBooth)
        self.logo2.setGeometry(QtCore.QRect(1770, 900, 150, 169))
        self.logo2.setText("")
        self.logo2.setPixmap(QtGui.QPixmap("ressources/logo_blanc_sur_transparent.png"))
        self.logo2.setScaledContents(True)
        self.logo2.setObjectName("logo2")
        self.background.raise_()
        self.loading.raise_()
        self.widgetPhoto.raise_()
        self.widgetPrint.raise_()
        self.logo1.raise_()
        self.logo2.raise_()
        self.compteur.raise_()
        self.veilleButton.raise_()
        self.widgetDevelopper.raise_()

        self.retranslateUi(PhotoBooth)
        QtCore.QMetaObject.connectSlotsByName(PhotoBooth)

    def retranslateUi(self, PhotoBooth):
        _translate = QtCore.QCoreApplication.translate
        PhotoBooth.setWindowTitle(_translate("PhotoBooth", "PhotoBooth"))
        self.compteur.setText(_translate("PhotoBooth", "654 photos restantes"))
        self.nbPrintLabel.setText(_translate("PhotoBooth", "10"))
        self.buttonIncrease.setText(_translate("PhotoBooth", ">"))
        self.buttonIncrease.setShortcut(_translate("PhotoBooth", "Alt+Return"))
        self.buttonDecrease.setText(_translate("PhotoBooth", "<"))
        self.buttonDecrease.setShortcut(_translate("PhotoBooth", "Alt+Return"))
        self.buttonExit.setShortcut(_translate("PhotoBooth", "Alt+Return"))
        self.warning.setText(_translate("PhotoBooth", "No warning/error"))
        self.countdown.setText(_translate("PhotoBooth", "10"))
        self.lookUp.setText(_translate("PhotoBooth", "Regardez ici ☝"))
        self.veilleButton.setText(_translate("PhotoBooth", "Toucher l\'écran pour démarrer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_photobooth = QtWidgets.QWidget()
    ui = Ui_PhotoBooth()
    ui.setupUi(new_photobooth)
    new_photobooth.show()
    sys.exit(app.exec_())
