# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photobooth.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

SCALE=1.5


class Ui_PhotoBooth(object):
    def setupUi(self, PhotoBooth):
        PhotoBooth.setObjectName("PhotoBooth")
        PhotoBooth.resize(1920, 1080)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(230, 187, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 187, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(226, 184, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        PhotoBooth.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(round(20/SCALE,0))
        font.setBold(True)
        font.setWeight(75)
        PhotoBooth.setFont(font)
        PhotoBooth.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.logo = QtWidgets.QLabel(PhotoBooth)
        self.logo.setGeometry(QtCore.QRect(1645, 25, 250, 281))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("ressources/logo_blanc_sur_transparent.png"))
        self.logo.setObjectName("logo")
        self.compteur = QtWidgets.QLabel(PhotoBooth)
        self.compteur.setGeometry(QtCore.QRect(1620, 1020, 300, 48))
        font = QtGui.QFont()
        font.setPointSize(round(36/SCALE,0))
        self.compteur.setFont(font)
        self.compteur.setAlignment(QtCore.Qt.AlignCenter)
        self.compteur.setObjectName("compteur")
        self.loading = QtWidgets.QLabel(PhotoBooth)
        self.loading.setGeometry(QtCore.QRect(610, 340, 400, 400))
        self.loading.setText("")
        self.loading.setObjectName("loading")
        self.background = QtWidgets.QLabel(PhotoBooth)
        self.background.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Forfty Scribble")
        font.setBold(True)
        font.setWeight(75)
        self.background.setFont(font)
        self.background.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(222, 180, 163, 255), stop:1 rgba(242, 199, 183, 255));")
        self.background.setText("")
        self.background.setObjectName("background")
        self.widgetPrint = QtWidgets.QWidget(PhotoBooth)
        self.widgetPrint.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.widgetPrint.setObjectName("widgetPrint")
        self.nbPrintLabel = QtWidgets.QLabel(self.widgetPrint)
        self.nbPrintLabel.setGeometry(QtCore.QRect(1680, 300, 180, 150))
        font = QtGui.QFont()
        font.setPointSize(round(100/SCALE,0))
        self.nbPrintLabel.setFont(font)
        self.nbPrintLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nbPrintLabel.setObjectName("nbPrintLabel")
        self.buttonIncrease = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonIncrease.setGeometry(QtCore.QRect(1800, 320, 61, 111))
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(round(60/SCALE,0))
        font.setBold(True)
        font.setWeight(75)
        self.buttonIncrease.setFont(font)
        self.buttonIncrease.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.buttonIncrease.setObjectName("buttonIncrease")
        self.buttonPrinter = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonPrinter.setGeometry(QtCore.QRect(1680, 450, 180, 180))
        font = QtGui.QFont()
        font.setPointSize(round(72/SCALE,0))
        self.buttonPrinter.setFont(font)
        self.buttonPrinter.setAutoFillBackground(False)
        self.buttonPrinter.setStyleSheet("background-color: transparent;")
        self.buttonPrinter.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/boutonPrinter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrinter.setIcon(icon)
        self.buttonPrinter.setIconSize(QtCore.QSize(180, 180))
        self.buttonPrinter.setObjectName("buttonPrinter")
        self.buttonRestart = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonRestart.setGeometry(QtCore.QRect(1680, 640, 180, 180))
        font = QtGui.QFont()
        font.setPointSize(round(72/SCALE,0))
        self.buttonRestart.setFont(font)
        self.buttonRestart.setAutoFillBackground(False)
        self.buttonRestart.setStyleSheet("background-color: transparent;")
        self.buttonRestart.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ressources/boutonRestart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRestart.setIcon(icon1)
        self.buttonRestart.setIconSize(QtCore.QSize(180, 180))
        self.buttonRestart.setObjectName("buttonRestart")
        self.buttonCancel = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonCancel.setGeometry(QtCore.QRect(1680, 830, 180, 180))
        font = QtGui.QFont()
        font.setPointSize(round(72/SCALE,0))
        self.buttonCancel.setFont(font)
        self.buttonCancel.setAutoFillBackground(False)
        self.buttonCancel.setStyleSheet("background-color: transparent;")
        self.buttonCancel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ressources/boutonCancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCancel.setIcon(icon2)
        self.buttonCancel.setIconSize(QtCore.QSize(180, 180))
        self.buttonCancel.setObjectName("buttonCancel")
        self.buttonDecrease = QtWidgets.QPushButton(self.widgetPrint)
        self.buttonDecrease.setGeometry(QtCore.QRect(1680, 320, 61, 111))
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(round(60/SCALE,0))
        font.setBold(True)
        font.setWeight(75)
        self.buttonDecrease.setFont(font)
        self.buttonDecrease.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.buttonDecrease.setObjectName("buttonDecrease")
        self.viewer = QtWidgets.QLabel(self.widgetPrint)
        self.viewer.setGeometry(QtCore.QRect(0, 0, 1620, 1080))
        self.viewer.setAutoFillBackground(False)
        self.viewer.setText("")
        self.viewer.setObjectName("viewer")
        self.widgetDevelopper = QtWidgets.QWidget(PhotoBooth)
        self.widgetDevelopper.setGeometry(QtCore.QRect(0, 970, 241, 111))
        self.widgetDevelopper.setObjectName("widgetDevelopper")
        self.buttonExit = QtWidgets.QPushButton(self.widgetDevelopper)
        self.buttonExit.setGeometry(QtCore.QRect(0, 40, 241, 71))
        self.buttonExit.setStyleSheet("background-color: transparent;")
        self.buttonExit.setText("")
        self.buttonExit.setObjectName("buttonExit")
        self.warning = QtWidgets.QLabel(self.widgetDevelopper)
        self.warning.setGeometry(QtCore.QRect(10, 0, 161, 31))
        self.warning.setObjectName("warning")
        self.widgetPhoto = QtWidgets.QWidget(PhotoBooth)
        self.widgetPhoto.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.widgetPhoto.setObjectName("widgetPhoto")
        self.buttonPhoto = QtWidgets.QPushButton(self.widgetPhoto)
        self.buttonPhoto.setGeometry(QtCore.QRect(1680, 460, 180, 180))
        font = QtGui.QFont()
        font.setPointSize(round(72/SCALE,0))
        self.buttonPhoto.setFont(font)
        self.buttonPhoto.setAutoFillBackground(False)
        self.buttonPhoto.setStyleSheet("background-color: transparent;")
        self.buttonPhoto.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ressources/boutonPhoto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPhoto.setIcon(icon3)
        self.buttonPhoto.setIconSize(QtCore.QSize(180, 180))
        self.buttonPhoto.setObjectName("buttonPhoto")
        self.countdown = QtWidgets.QLabel(self.widgetPhoto)
        self.countdown.setGeometry(QtCore.QRect(0, -100, 1620, 700))
        font = QtGui.QFont()
        font.setPointSize(round(500/SCALE,0))
        self.countdown.setFont(font)
        self.countdown.setAlignment(QtCore.Qt.AlignCenter)
        self.countdown.setObjectName("countdown")
        self.camView = QtWidgets.QLabel(self.widgetPhoto)
        self.camView.setGeometry(QtCore.QRect(0, 0, 1620, 1080))
        self.camView.setAutoFillBackground(False)
        self.camView.setText("")
        self.camView.setObjectName("camView")
        self.lookUp = QtWidgets.QLabel(self.widgetPhoto)
        self.lookUp.setGeometry(QtCore.QRect(0, 0, 1620, 280))
        font = QtGui.QFont()
        font.setPointSize(round(160/SCALE,0))
        self.lookUp.setFont(font)
        self.lookUp.setAlignment(QtCore.Qt.AlignCenter)
        self.lookUp.setObjectName("lookUp")
        self.buttonPhoto.raise_()
        self.camView.raise_()
        self.countdown.raise_()
        self.lookUp.raise_()
        self.veilleButton = QtWidgets.QPushButton(PhotoBooth)
        self.veilleButton.setGeometry(QtCore.QRect(-20, -20, 1960, 1120))
        font = QtGui.QFont()
        font.setFamily("Amatic")
        font.setPointSize(round(72/SCALE,0))
        self.veilleButton.setFont(font)
        self.veilleButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(222, 180, 163, 255), stop:1 rgba(242, 199, 183, 255));\n"
"color: rgb(255, 255, 255);")
        self.veilleButton.setObjectName("veilleButton")
        self.background.raise_()
        self.loading.raise_()
        self.logo.raise_()
        self.compteur.raise_()
        self.widgetPhoto.raise_()
        self.widgetDevelopper.raise_()
        self.widgetPrint.raise_()
        self.veilleButton.raise_()

        self.retranslateUi(PhotoBooth)
        QtCore.QMetaObject.connectSlotsByName(PhotoBooth)

    def retranslateUi(self, PhotoBooth):
        _translate = QtCore.QCoreApplication.translate
        PhotoBooth.setWindowTitle(_translate("PhotoBooth", "PhotoBooth"))
        self.compteur.setText(_translate("PhotoBooth", "654 photos restantes"))
        self.nbPrintLabel.setText(_translate("PhotoBooth", "10"))
        self.buttonIncrease.setText(_translate("PhotoBooth", ">"))
        self.buttonIncrease.setShortcut(_translate("PhotoBooth", "Alt+Return"))
        self.buttonDecrease.setText(_translate("PhotoBooth", "<"))
        self.buttonDecrease.setShortcut(_translate("PhotoBooth", "Alt+Return"))
        self.buttonExit.setShortcut(_translate("PhotoBooth", "Alt+Return"))
        self.warning.setText(_translate("PhotoBooth", "No warning/error"))
        self.countdown.setText(_translate("PhotoBooth", "10"))
        self.lookUp.setText(_translate("PhotoBooth", "Regardez ici ☝"))
        self.veilleButton.setText(_translate("PhotoBooth", "Toucher l\'écran pour démarrer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PhotoBooth = QtWidgets.QWidget()
    ui = Ui_PhotoBooth()
    ui.setupUi(PhotoBooth)
    PhotoBooth.show()
    sys.exit(app.exec_())
